USER INFO
{
    "login": "SavageWilliam",   //username
    "id": 15717822,
    "avatar_url": "https://avatars.githubusercontent.com/u/15717822?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/SavageWilliam",  //link
    "html_url": "https://github.com/SavageWilliam",
    "followers_url": "https://api.github.com/users/SavageWilliam/followers",
    "following_url": "https://api.github.com/users/SavageWilliam/following{/other_user}",
    "gists_url": "https://api.github.com/users/SavageWilliam/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/SavageWilliam/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/SavageWilliam/subscriptions",
    "organizations_url": "https://api.github.com/users/SavageWilliam/orgs",
    "repos_url": "https://api.github.com/users/SavageWilliam/repos",
    "events_url": "https://api.github.com/users/SavageWilliam/events{/privacy}",
    "received_events_url": "https://api.github.com/users/SavageWilliam/received_events",
    "type": "User",
    "site_admin": false,
    "name": "William Savage",    //name
    "company": null,
    "blog": null,
    "location": "London",
    "email": "willsavage@hotmail.com",
    "hireable": null,
    "bio": "Full stack JavaScript developer in training @foundersandcoders . https://facu-autocompleter.herokuapp.com/ Heroku project",
    "public_repos": 20,    //repos
    "public_gists": 0,
    "followers": 6,
    "following": 5,
    "created_at": "2015-11-08T17:33:31Z",
    "updated_at": "2016-12-06T11:12:55Z"
}


ISSUES

[
  {
    "id": 1,
    "url": "https://api.github.com/repos/octocat/Hello-World/issues/1347",
    "repository_url": "https://api.github.com/repos/octocat/Hello-World",
    "labels_url": "https://api.github.com/repos/octocat/Hello-World/issues/1347/labels{/name}",
    "comments_url": "https://api.github.com/repos/octocat/Hello-World/issues/1347/comments",
    "events_url": "https://api.github.com/repos/octocat/Hello-World/issues/1347/events",
    "html_url": "https://github.com/octocat/Hello-World/issues/1347",
    "number": 1347,
    "state": "open",   //state
    "title": "Found a bug",  //title
    "body": "I'm having a problem with this.",
    "user": {
      "login": "octocat",
      "id": 1,
      "avatar_url": "https://github.com/images/error/octocat_happy.gif",
      "gravatar_id": "",
      "url": "https://api.github.com/users/octocat",
      "html_url": "https://github.com/octocat",
      "followers_url": "https://api.github.com/users/octocat/followers",
      "following_url": "https://api.github.com/users/octocat/following{/other_user}",
      "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
      "organizations_url": "https://api.github.com/users/octocat/orgs",
      "repos_url": "https://api.github.com/users/octocat/repos",
      "events_url": "https://api.github.com/users/octocat/events{/privacy}",
      "received_events_url": "https://api.github.com/users/octocat/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 208045946,
        "url": "https://api.github.com/repos/octocat/Hello-World/labels/bug",
        "name": "bug",
        "color": "f29513",
        "default": true
      }
    ],
    "assignee": {
      "login": "octocat",
      "id": 1,
      "avatar_url": "https://github.com/images/error/octocat_happy.gif",
      "gravatar_id": "",
      "url": "https://api.github.com/users/octocat",
      "html_url": "https://github.com/octocat",
      "followers_url": "https://api.github.com/users/octocat/followers",
      "following_url": "https://api.github.com/users/octocat/following{/other_user}",
      "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
      "organizations_url": "https://api.github.com/users/octocat/orgs",
      "repos_url": "https://api.github.com/users/octocat/repos",
      "events_url": "https://api.github.com/users/octocat/events{/privacy}",
      "received_events_url": "https://api.github.com/users/octocat/received_events",
      "type": "User",
      "site_admin": false
    },
    "milestone": {
      "url": "https://api.github.com/repos/octocat/Hello-World/milestones/1",
      "html_url": "https://github.com/octocat/Hello-World/milestones/v1.0",
      "labels_url": "https://api.github.com/repos/octocat/Hello-World/milestones/1/labels",
      "id": 1002604,
      "number": 1,
      "state": "open",
      "title": "v1.0",
      "description": "Tracking milestone for version 1.0",
      "creator": {
        "login": "octocat",
        "id": 1,
        "avatar_url": "https://github.com/images/error/octocat_happy.gif",
        "gravatar_id": "",
        "url": "https://api.github.com/users/octocat",
        "html_url": "https://github.com/octocat",
        "followers_url": "https://api.github.com/users/octocat/followers",
        "following_url": "https://api.github.com/users/octocat/following{/other_user}",
        "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
        "organizations_url": "https://api.github.com/users/octocat/orgs",
        "repos_url": "https://api.github.com/users/octocat/repos",
        "events_url": "https://api.github.com/users/octocat/events{/privacy}",
        "received_events_url": "https://api.github.com/users/octocat/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 4,
      "closed_issues": 8,
      "created_at": "2011-04-10T20:09:31Z",
      "updated_at": "2014-03-03T18:58:10Z",
      "closed_at": "2013-02-12T13:22:01Z",
      "due_on": "2012-10-09T23:39:01Z"
    },
    "locked": false,
    "comments": 0,
    "pull_request": {
      "url": "https://api.github.com/repos/octocat/Hello-World/pulls/1347",
      "html_url": "https://github.com/octocat/Hello-World/pull/1347",
      "diff_url": "https://github.com/octocat/Hello-World/pull/1347.diff",
      "patch_url": "https://github.com/octocat/Hello-World/pull/1347.patch"
    },
    "closed_at": null,
    "created_at": "2011-04-22T13:33:48Z",
    "updated_at": "2011-04-22T13:33:48Z"
  }
]
//ISSUE FROM fetchSaveIssues
{   url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/issues/38',
    repository_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing',
    labels_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/issues/38/labels{/name}',
    comments_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/issues/38/comments',
    events_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/issues/38/events',
    html_url: 'https://github.com/foundersandcoders/resource-sharing/issues/38',
    id: 192558137,
    number: 38,
    title: '\'/createResource\' form for user to add new resource',
    user:
     { login: 'SavageWilliam',
       id: 15717822,
       avatar_url: 'https://avatars.githubusercontent.com/u/15717822?v=3',
       gravatar_id: '',
       url: 'https://api.github.com/users/SavageWilliam',
       html_url: 'https://github.com/SavageWilliam',
       followers_url: 'https://api.github.com/users/SavageWilliam/followers',
       following_url: 'https://api.github.com/users/SavageWilliam/following{/other_user}',
       gists_url: 'https://api.github.com/users/SavageWilliam/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/SavageWilliam/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/SavageWilliam/subscriptions',
       organizations_url: 'https://api.github.com/users/SavageWilliam/orgs',
       repos_url: 'https://api.github.com/users/SavageWilliam/repos',
       events_url: 'https://api.github.com/users/SavageWilliam/events{/privacy}',
       received_events_url: 'https://api.github.com/users/SavageWilliam/received_events',
       type: 'User',
       site_admin: false },
    labels: [],
    state: 'closed',
    locked: false,
    assignee:
     { login: 'stevehopkinson',
       id: 5929394,
       avatar_url: 'https://avatars.githubusercontent.com/u/5929394?v=3',
       gravatar_id: '',
       url: 'https://api.github.com/users/stevehopkinson',
       html_url: 'https://github.com/stevehopkinson',
       followers_url: 'https://api.github.com/users/stevehopkinson/followers',
       following_url: 'https://api.github.com/users/stevehopkinson/following{/other_user}',
       gists_url: 'https://api.github.com/users/stevehopkinson/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/stevehopkinson/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/stevehopkinson/subscriptions',
       organizations_url: 'https://api.github.com/users/stevehopkinson/orgs',
       repos_url: 'https://api.github.com/users/stevehopkinson/repos',
       events_url: 'https://api.github.com/users/stevehopkinson/events{/privacy}',
       received_events_url: 'https://api.github.com/users/stevehopkinson/received_events',
       type: 'User',
       site_admin: false },
    assignees: [ [Object], [Object] ],
    milestone: null,
    comments: 0,
    created_at: '2016-11-30T12:53:07Z',
    updated_at: '2016-11-30T17:42:27Z',
    closed_at: '2016-11-30T17:42:27Z',
    repository:
     { id: 75063417,
       name: 'resource-sharing',
       full_name: 'foundersandcoders/resource-sharing',
       owner: [Object],
       private: false,
       html_url: 'https://github.com/foundersandcoders/resource-sharing',
       description: null,
       fork: false,
       url: 'https://api.github.com/repos/foundersandcoders/resource-sharing',
       forks_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/forks',
       keys_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/keys{/key_id}',
       collaborators_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/collaborators{/collaborator}',
       teams_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/teams',
       hooks_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/hooks',
       issue_events_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/issues/events{/number}',
       events_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/events',
       assignees_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/assignees{/user}',
       branches_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/branches{/branch}',
       tags_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/tags',
       blobs_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/git/blobs{/sha}',
       git_tags_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/git/tags{/sha}',
       git_refs_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/git/refs{/sha}',
       trees_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/git/trees{/sha}',
       statuses_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/statuses/{sha}',
       languages_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/languages',
       stargazers_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/stargazers',
       contributors_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/contributors',
       subscribers_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/subscribers',
       subscription_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/subscription',
       commits_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/commits{/sha}',
       git_commits_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/git/commits{/sha}',
       comments_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/comments{/number}',
       issue_comment_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/issues/comments{/number}',
       contents_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/contents/{+path}',
       compare_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/compare/{base}...{head}',
       merges_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/merges',
       archive_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/{archive_format}{/ref}',
       downloads_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/downloads',
       issues_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/issues{/number}',
       pulls_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/pulls{/number}',
       milestones_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/milestones{/number}',
       notifications_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/notifications{?since,all,participating}',
       labels_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/labels{/name}',
       releases_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/releases{/id}',
       deployments_url: 'https://api.github.com/repos/foundersandcoders/resource-sharing/deployments',
       created_at: '2016-11-29T09:10:27Z',
       updated_at: '2016-12-04T21:38:14Z',
       pushed_at: '2016-12-05T00:55:34Z',
       git_url: 'git://github.com/foundersandcoders/resource-sharing.git',
       ssh_url: 'git@github.com:foundersandcoders/resource-sharing.git',
       clone_url: 'https://github.com/foundersandcoders/resource-sharing.git',
       svn_url: 'https://github.com/foundersandcoders/resource-sharing',
       homepage: null,
       size: 637,
       stargazers_count: 2,
       watchers_count: 2,
       language: 'JavaScript',
       has_issues: true,
       has_downloads: true,
       has_wiki: true,
       has_pages: false,
       forks_count: 2,
       mirror_url: null,
       open_issues_count: 34,
       forks: 2,
       open_issues: 34,
       watchers: 2,
       default_branch: 'master' },
    body: '' },
